# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Room
email: chris@prather.org
description: > # this means to ignore newlines until "baseurl:"
 In the room women come and go speaking of Michaelangelo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chris.prather.org" # the base hostname & protocol for your site
twitter_username: perigrin
github_username:  perigrin

# Build settings
markdown: kramdown
gems:
    - jekyll-paginate
    - jekyll-seo-tag
    - jemoji

paginate: 5
paginate_path: "/:num/"
