# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'CV', path: 'menu', url: 'cv.html'}
- {name: 'Colophon', path: 'menu', url: 'colophon.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {pre: 'solid', icon: 'circle-dollar-to-slot', link: 'https://github.com/sponsors/perigrin'}
- {pre: 'brands', icon: 'github', link: 'https://www.github.com/perigrin'}
- {pre: 'brands', icon: 'mastodon', link: 'https://ack.nerdfight.online/perigrin'}
- {pre: 'solid', icon: 'envelope', link: 'mailto:chris@prather.org'}
- {pre: 'solid', icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
