name: Spellcheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.9.1
